# Generated by Django 4.2.20 on 2025-04-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='socialmediaurls',
            table='core_socialmediaurls',
        ),
    ]
