# Generated by Django 4.2.20 on 2025-04-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passwordresetcode_delete_passwordreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
