# Generated by Django 4.2.20 on 2025-04-21 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_passwordresetcode_useractivitylog_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='ip_address',
        ),
        migrations.CreateModel(
            name='CareerApplications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('cv_link', models.URLField(max_length=500, verbose_name='CV Google Drive Link')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.careers')),
            ],
            options={
                'verbose_name': 'Career Application',
                'verbose_name_plural': 'Career Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
