# Generated by Django 4.2.20 on 2025-04-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_useractivitylog_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
